SQL> SELECT DISTINCT(m.ModuleName),ClassID
  2  FROM Module m
  3  GROUP BY m.ModuleName,ClassID
  4  HAVING COUNT (m.ClassID)=1;

MODULENAME           CLASSID                                                                                                                                                                                                                                                                                                                                                                                    
-------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                 
Emerging Programming P1                                                                                                                                                                                                                                                                                                                                                                                         
Database             K1                                                                                                                                                                                                                                                                                                                                                                                         
Software Engineering P2                                                                                                                                                                                                                                                                                                                                                                                         
 Linux               Y1                                                                                                                                                                                                                                                                                                                                                                                         
 NOS                 O1                                                                                                                                                                                                                                                                                                                                                                                         
 Logic and Problems  N1                                                                                                                                                                                                                                                                                                                                                                                         
 Software            Y1                                                                                                                                                                                                                                                                                                                                                                                         

7 rows selected.

SQL> spool off;
