SQL> SELECT PhoneNo2,
  2  NVL(PhoneNo2,1234567890) AS "ContactDetails"
  3  FROM InstructorAddress;

  PHONENO2 ContactDetails                                                                                                                                                                                                                                                                                                                                                                                       
---------- --------------                                                                                                                                                                                                                                                                                                                                                                                       
9877626261     9877626261                                                                                                                                                                                                                                                                                                                                                                                       
               1234567890                                                                                                                                                                                                                                                                                                                                                                                       
               1234567890                                                                                                                                                                                                                                                                                                                                                                                       
9988654450     9988654450                                                                                                                                                                                                                                                                                                                                                                                       
9000888099     9000888099                                                                                                                                                                                                                                                                                                                                                                                       
9877778778     9877778778                                                                                                                                                                                                                                                                                                                                                                                       
               1234567890                                                                                                                                                                                                                                                                                                                                                                                       

7 rows selected.

SQL> spool off;
