SQL> SELECT NAME,(SYSDATE-EnrolledDate)/7 AS "Weeks since Enrollment"
  2  FROM Student;

NAME                 Weeks since Enrollment                                                                                                                                                                                                                                                                                                                                                                     
-------------------- ----------------------                                                                                                                                                                                                                                                                                                                                                                     
Srijan Adhikari                  34.6573214                                                                                                                                                                                                                                                                                                                                                                     
Grisha Giri                      34.8001786                                                                                                                                                                                                                                                                                                                                                                     
Rajin Shrestha                   34.9430357                                                                                                                                                                                                                                                                                                                                                                     
Helina Khanal                    35.0858929                                                                                                                                                                                                                                                                                                                                                                     
Prajna Subedi                    83.3716071                                                                                                                                                                                                                                                                                                                                                                     
Rojan Shrestha                   108.943036                                                                                                                                                                                                                                                                                                                                                                     
Priyanka Shrestha                156.943036                                                                                                                                                                                                                                                                                                                                                                     

7 rows selected.

SQL> spool off;
